import subprocess
import time
import os
import sys

# רשימת התרחישים המלאה והמפורטת
scenarios = [
    # שלב 1: הרצה ראשונה על כל HASH_CODE בלי הגנות
    {"name": "01_pure_sha256", "hash": "sha256_salt", "pep": False, "totp": False, "rate": False, "lock": False,
     "caps": False},
    {"name": "02_pure_argon2", "hash": "argon2id", "pep": False, "totp": False, "rate": False, "lock": False,
     "caps": False},
    {"name": "03_pure_bcrypt", "hash": "bcrypt", "pep": False, "totp": False, "rate": False, "lock": False,
     "caps": False},

    # שלב 2: הוספת כל הגנה בנפרד
    # נשתמש ב-Bcrypt כבסיס להשוואה מכאן והלאה
    {"name": "04_protect_pepper_only", "hash": "sha256_salt", "pep": True, "totp": False, "rate": False, "lock": False,
     "caps": False},
    {"name": "05_protect_totp_only", "hash": "sha256_salt", "pep": False, "totp": True, "rate": False, "lock": False,
     "caps": False},
    {"name": "06_protect_rate_only", "hash": "sha256_salt", "pep": False, "totp": False, "rate": True, "lock": False,
     "caps": False},
    {"name": "07_protect_lockout_only", "hash": "sha256_salt", "pep": False, "totp": False, "rate": False, "lock": True,
     "caps": False},
    {"name": "08_protect_captcha_only", "hash": "sha256_salt", "pep": False, "totp": False, "rate": False, "lock": False,
     "caps": True},

    # שלב 3: שילובים (וריאציות)
    {"name": "09_var_hashing_plus_active", "hash": "ha256_salt", "pep": True, "totp": False, "rate": True, "lock": True,
     "caps": False},
    {"name": "10_full_defense_all_on", "hash": "ha256_salt", "pep": True, "totp": True, "rate": True, "lock": True,
     "caps": True},
]

def update_config(hash_mode, pep, totp, rate, lock, caps):
    """מעדכן את קובץ ה-config עם כל המשתנים שהשרת וה-DB צריכים"""
    config_content = f"""
# This file is auto-generated by Orchestrator
GROUP_SEED = 527740437
HASH_MODE = "{hash_mode}"
BCRYPT_COST = 12
PEPPER = "SuperSecretPepper123!"
DB_PATH = "users.db"  # השורה שהייתה חסרה וגרמה לקריסה
ADMIN_KEY = "super_admin_key"
CAPTCHA_FAIL = 3
CAPTCHA_TIME = 60
LOCKOUT_TRY = 3
LOCKOUT_TIME = 300
RATE_LIMIT_TRY = 5
RATE_REFILL = 0.1
RATE_HARD_LOCK = True

PROTECTION_FLAGS = {{
    "pepper": {pep},
    "totp": {totp},
    "rate_limit": {rate},
    "lockout": {lock},
    "captcha": {caps}
}}
"""
    with open("config.py", "w", encoding="utf-8") as f:
        f.write(config_content)

def run_experiment():
    # 1. הכנות בסיסיות
    if not os.path.exists("results"):
        os.makedirs("results")
        print("[*] Created 'results' folder.")

    for sc in scenarios:
        print(f"\n{'=' * 60}\n[!] STARTING SCENARIO: {sc['name']}\n{'=' * 60}")

        # 2. עדכון קובץ ה-Config לפי התרחיש הנוכחי
        update_config(sc['hash'], sc['pep'], sc['totp'], sc['rate'], sc['lock'], sc['caps'])

        # 3. ניקוי בסיס הנתונים (כדי להתחיל דף חלק בכל פעם)
        db_path = "users.db"
        if os.path.exists(db_path):
            try:
                os.remove(db_path)
                print(f"[V] Database reset for {sc['name']}.")
            except Exception as e:
                print(f"[X] Could not delete DB: {e}. Make sure no other process uses it.")
                continue

        # 4. הפעלת השרת (app.py)
        print(f"[*] Launching server (app.py)...")
        server_proc = subprocess.Popen([sys.executable, "app.py"])

        # המתנה קצרה כדי לוודא שה-Flask עלה והפורט 5000 פתוח
        time.sleep(5)

        # 5. הרצת setup_experiment.py - כעת כשהשרת רץ, הרישום יעבור בהצלחה
        print("[*] Running setup_experiment.py to register users and create users.json...")
        try:
            # check=True יגרום לסקריפט לעצור אם ה-Setup נכשל
            subprocess.run([sys.executable, "setup_experiment.py"], check=True)
            print("[V] Setup completed successfully.")
        except subprocess.CalledProcessError:
            print("[X] Setup failed! Killing server and moving to next scenario.")
            server_proc.terminate()
            continue

        # 6. הרצת התוקף (attacker.py)
        log_file = os.path.join("results", f"res_{sc['name']}.csv")
        print(f"[*] Attacker starts! Results will be in: {log_file}")

        try:
            # מריצים את התוקף ומחכים שיסיים את כל הניסיונות שלו
            subprocess.run([sys.executable, "attacker.py", log_file], check=True)
            print(f"[V] Attack on {sc['name']} finished.")
        except subprocess.CalledProcessError as e:
            print(f"[X] Attacker encountered an error: {e}")

        # 7. סגירת השרת בבטחה
        print(f"[*] Shutting down server...")
        server_proc.terminate()
        try:
            server_proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            server_proc.kill()

        print(f"[V] Scenario {sc['name']} is done.")
        # הפסקה קצרה כדי לאפשר למערכת ההפעלה לשחרר את הפורט (Socket)
        time.sleep(2)

    print("\n" + "#" * 60 + "\n[!!!] ALL EXPERIMENTS COMPLETED! Check the 'results' folder. \n" + "#" * 60)

if __name__ == "__main__":
    run_experiment()
    print("\n[!!!] DONE! All results are in the 'results' folder [!!!]")